version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sammessage"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gkcve9sqxgwu"
s3_prefix = "sammessage"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

